#!/bin/bash
# ------------------------------------------------------------------
# OmniCloud Bootstrap Script
# Linked via Terraform User Data
# ------------------------------------------------------------------

set -e
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

echo "[Bootstrap] Starting node provisioning for cluster: test..."

# 1. Install Dependencies
echo "[Bootstrap] Installing Puppet and Git..."
if [ -x "$(command -v apt-get)" ]; then
  apt-get update -y
  apt-get install -y git puppet-agent
elif [ -x "$(command -v yum)" ]; then
  yum install -y git puppet-agent
fi

# 2. Clone Infrastructure Repo (The "Handshake")
echo "[Bootstrap] Cloning GitOps repository..."
mkdir -p /opt/omnicloud
cd /opt/omnicloud
# In prod, you would use a Deploy Token or SSH Key here
git clone https://github.com/Gorak4u/infra-ops.git . 

# 3. Run Puppet
echo "[Bootstrap] Applying Puppet Configuration..."
# This applies the manifest generated by the frontend
/opt/puppetlabs/bin/puppet apply /opt/omnicloud/clusters/test/puppet/manifest.pp

echo "[Bootstrap] Provisioning Complete. Node is ready."
