# Auto-generated by OmniCloud Ops at 2025-12-09T12:22:20.787Z
# Cluster: test


provider "google" {
  project = "default-project"
  region  = "us-east-1"
}

module "cassandra_cluster" {
  source = "github.com/Gorak4u/terraform-google-cassandra"

  name            = "test"
  machine_type    = "r5.2xlarge"
  node_count      = 3
  
  network         = "analytics-vpc"
  subnetwork      = "analytics-subnet-us-east1"
  
  disk_size_gb    = 1000
  disk_type       = "gp3"
  
  service_account = ""
  
  labels = {
    managedby = "omnicloud"
    costcenter = "infraops"
    managed_by = "omnicloud"
  }
}
