#!/bin/bash
# ------------------------------------------------------------------
# OmniCloud Bootstrap Script (UBUNTU)
# Linked via Terraform User Data
# ------------------------------------------------------------------

set -e
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

echo "[Bootstrap] Starting node provisioning for cluster: prod..."

# 1. Install Dependencies & Puppet Agent v7
echo "[Bootstrap] Installing Puppet Agent..."
wget https://apt.puppet.com/puppet7-release-focal.deb && dpkg -i $(basename https://apt.puppet.com/puppet7-release-focal.deb) && apt-get update && apt-get install -y git puppet-agent

# 2. Clone Infrastructure Repo (The "Handshake")
echo "[Bootstrap] Cloning GitOps repository..."
mkdir -p /opt/omnicloud
cd /opt/omnicloud
# In prod, use Deploy Token or SSH Key
git clone https://github.com/Gorak4u/infra-ops.git . 

# 3. Apply Puppet Configuration
echo "[Bootstrap] Applying Puppet Configuration..."
# This applies the manifest generated by the frontend
/opt/puppetlabs/bin/puppet apply /opt/omnicloud/clusters/prod/puppet/manifest.pp

echo "[Bootstrap] Provisioning Complete. Node is ready."
