#!/bin/bash
# ------------------------------------------------------------------
# OmniCloud Enterprise Bootstrap (UBUNTU)
# Cluster: prod
# Generated by OmniCloud Ops
# ------------------------------------------------------------------
set -e
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

echo "[Bootstrap] Initializing node provisioning..."

# --- 1. Kernel & OS Tuning for Cassandra (Production Best Practices) ---
echo "[Bootstrap] Applying Kernel Tuning..."
cat <<EOF > /etc/sysctl.d/99-cassandra.conf
vm.max_map_count = 1048575
vm.swappiness = 1
net.ipv4.tcp_keepalive_time = 60
net.ipv4.tcp_keepalive_probes = 3
net.ipv4.tcp_keepalive_intvl = 10
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
fs.file-max = 1000000
EOF
sysctl -p /etc/sysctl.d/99-cassandra.conf

# Disable swap
swapoff -a
# Fixed: Use simpler sed command to avoid JS octal escape issues with backreferences
sed -i '/ swap / s/^/#/' /etc/fstab

# --- 2. Configure User Limits ---
echo "[Bootstrap] Configuring Limits..."
cat <<EOF > /etc/security/limits.d/cassandra.conf
cassandra - memlock unlimited
cassandra - nofile 100000
cassandra - nproc 32768
cassandra - as unlimited
root - memlock unlimited
root - nofile 100000
root - nproc 32768
EOF

# --- 3. Storage Setup (XFS Formatting & Mounting) ---
# Auto-detect unformatted NVMe or EBS volumes for data
echo "[Bootstrap] Configuring Storage..."
# Find first disk that is not root (xvda/nvme0n1) and not mounted
DATA_DISK=$(lsblk -dn -o NAME | grep -E "nvme[1-9]n1|xvd[b-z]|sd[b-z]" | head -1)

if [ ! -z "$DATA_DISK" ]; then
    echo "Found data disk: /dev/$DATA_DISK"
    # Check if has filesystem
    if ! blkid /dev/$DATA_DISK; then
        echo "Formatting /dev/$DATA_DISK with XFS..."
        mkfs.xfs -f -K /dev/$DATA_DISK
    fi
    
    mkdir -p /var/lib/cassandra
    
    # Add to fstab if not exists
    if ! grep -q "/dev/$DATA_DISK" /etc/fstab; then
        echo "/dev/$DATA_DISK /var/lib/cassandra xfs defaults,noatime,nofail,allocsize=16M 0 2" >> /etc/fstab
    fi
    
    mount -a
    
    # Optimize block device (Read-ahead)
    blockdev --setra 128 /dev/$DATA_DISK
    
    # Ensure permissions
    groupadd -f cassandra
    useradd -g cassandra --no-create-home --shell /bin/false cassandra || true
    chown -R cassandra:cassandra /var/lib/cassandra
else
    echo "WARNING: No dedicated data disk found. Using root volume for data (NOT RECOMMENDED FOR PROD)."
fi

# --- 4. Install Dependencies ---
echo "[Bootstrap] Installing Software..."
wget https://apt.puppet.com/puppet7-release-focal.deb && dpkg -i $(basename https://apt.puppet.com/puppet7-release-focal.deb) && apt-get update && apt-get install -y git puppet-agent xfsprogs chrony

# Ensure Chrony is running for Time Sync
systemctl enable --now chronyd

# --- 5. GitOps Handshake ---
echo "[Bootstrap] Cloning Infrastructure Repo..."
mkdir -p /opt/omnicloud
cd /opt/omnicloud
# In prod, this would use a Deploy Token injected via Secrets Manager or UserData
git clone https://github.com/Gorak4u/infra-ops.git . 

# --- 6. Apply Puppet ---
echo "[Bootstrap] Applying Configuration..."
# Run Puppet Apply against the cluster-specific manifest
/opt/puppetlabs/bin/puppet apply /opt/omnicloud/clusters/prod/puppet/manifest.pp

echo "[Bootstrap] Complete. Node Ready."
