
# Puppet Manifest for ggonda-test-cassandra-cluster
# Generated by OmniCloud Ops

node default {
  include stdlib
  
  class { 'cassandra':
    cluster_name      => 'ggonda-test-cassandra-cluster',
    version           => '4.1.3',
    package_ensure    => '4.1.3',
    listen_interface  => 'eth0',
    rpc_interface     => 'eth0',
    seeds             => [],
    datacenter        => 'us-east-1',
    rack              => 'rack1',
    num_tokens        => 256,
  }

  class { 'java':
    distribution => 'jdk',
    version      => '11',
  }

  # Extra Packages
  package { ['htop', 'sysstat']:
    ensure => installed,
  }

  # Configuration Files
  file { '/etc/cassandra/cassandra.yaml':
    ensure  => file,
    content => template('cassandra/cassandra.yaml.erb'),
    require => Package['cassandra'],
    notify  => Service['cassandra'],
  }
  
  file { '/etc/cassandra/jvm.options':
    ensure  => file,
    content => lookup('cassandra::jvm_options'),
    require => Package['cassandra'],
    notify  => Service['cassandra'],
  }

  service { 'cassandra':
    ensure  => running,
    enable  => true,
    require => [File['/etc/cassandra/cassandra.yaml'], File['/etc/cassandra/jvm.options']],
  }
}
