
# ------------------------------------------------------------------
# Puppet Manifest for 
# Role: Cassandra Database Node
# Generated by OmniCloud Ops
# ------------------------------------------------------------------

node default {
  include stdlib
  include java

  # 1. System Limits & Sysctl (Enforcement)
  sysctl { 'vm.max_map_count': value => '1048575' }
  
  # 2. Install & Configure Cassandra
  class { 'cassandra':
    cluster_name      => '',
    version           => '4.1.3',
    package_ensure    => '4.1.3',
    listen_interface  => 'eth0',
    rpc_interface     => 'eth0',
    seeds             => [],
    dc                => 'us-east-1',
    rack              => 'rack1', # In prod, this is derived from ec2 facts
    num_tokens        => 256,
    
    # Directories (Mapped to XFS volumes)
    data_file_directories  => ['/var/lib/cassandra/data'],
    commitlog_directory    => '/var/lib/cassandra/commitlog',
    saved_caches_directory => '/var/lib/cassandra/saved_caches',
    hints_directory        => '/var/lib/cassandra/hints',
    
    # Tuning
    concurrent_reads       => 32,
    concurrent_writes      => 32,
    memtable_flush_writers => 4,
    
    # Config Management
    config_file_mode   => '0644',
    manage_config_file => false, # We use the file resource below for granular control
  }

  # 3. Dynamic Config Injection from Git (Allows UI to update specific files)
  file { '/etc/cassandra/cassandra.yaml':
    ensure  => file,
    content => file('/opt/omnicloud/clusters//conf/cassandra.yaml'),
    owner   => 'cassandra',
    group   => 'cassandra',
    mode    => '0644',
    require => Class['cassandra::install'],
    notify  => Class['cassandra::service'],
  }
  
  file { '/etc/cassandra/jvm.options':
    ensure  => file,
    content => file('/opt/omnicloud/clusters//conf/jvm.options'),
    owner   => 'cassandra',
    group   => 'cassandra',
    mode    => '0644',
    require => Class['cassandra::install'],
    notify  => Class['cassandra::service'],
  }

  # 4. Monitoring Agent
  if $::facts['monitoring_enabled'] == 'true' {
      class { 'prometheus::node_exporter': }
      class { 'cassandra::jmx_exporter': }
  }
  
  # 5. Extra Packages (Drivers/Tools)
  package { ['htop', 'sysstat']:
    ensure => installed,
  }

  # 6. Service State
  class { 'cassandra::service':
    ensure => running,
    enable => true,
  }
}
