# Auto-generated by OmniCloud Ops at 2025-12-09T16:03:20.191Z
# Cluster: prod
# Region: us-east-1

provider "aws" {
  region = "us-east-1"
  default_tags {
    tags = {
      ManagedBy   = "OmniCloud"
      Environment = "Production"
      Cluster     = "prod"
    }
  }
}

# --- IAM Role for Backups & Monitoring ---
resource "aws_iam_role" "cassandra_role" {
  name = "prod-node-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = { Service = "ec2.amazonaws.com" }
    }]
  })
}

resource "aws_iam_role_policy_attachment" "ssm_policy" {
  role       = aws_iam_role.cassandra_role.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

resource "aws_iam_instance_profile" "cassandra_profile" {
  name = "prod-profile"
  role = aws_iam_role.cassandra_role.name
}

# --- Security Group ---
resource "aws_security_group" "cassandra_sg" {
  name        = "prod-sg"
  description = "Security group for Cassandra Cluster prod"
  vpc_id      = "vpc-0a1b2c3d"

  # Inter-node Communication (Gossip/SSL)
  ingress {
    from_port = 7000
    to_port   = 7001
    protocol  = "tcp"
    self      = true
  }

  # Client Access
  ingress {
    from_port   = 9042
    to_port     = 9042
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  # SSH (Bastion only recommended in prod)
  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["10.0.0.0/8"] 
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

# --- Compute Module ---
module "cassandra_fleet" {
  source  = "terraform-aws-modules/ec2-instance/aws"
  version = "~> 5.0"

  count = 3
  name  = "prod-node-${count.index + 1}"

  ami           = "ami-0c7217cdde317cfec" # Canonical Ubuntu 22.04 LTS (Example)
  instance_type = "r5.2xlarge"
  key_name      = "omnicloud-prod-key"
  
  vpc_security_group_ids = [aws_security_group.cassandra_sg.id]
  subnet_id              = element(["subnet-1a","subnet-1b","subnet-1c"], count.index)
  iam_instance_profile   = aws_iam_instance_profile.cassandra_profile.name

  # Root Volume (OS)
  root_block_device = [{
    volume_size = 50
    volume_type = "gp3"
    encrypted   = true
    kms_key_id  = ""
  }]

  # Metadata Options (Security Best Practice)
  metadata_options = {
    http_endpoint               = "enabled"
    http_tokens                 = "required" # Enforce IMDSv2
    http_put_response_hop_limit = 1
  }

  # User Data (Bootstrap)
  user_data = file("${path.module}/../../bootstrap.sh")
  user_data_replace_on_change = true

  tags = {
    Rack = "rack-${(count.index % 3) + 1}"
  }
}

# --- Data Volumes (Attached EBS) ---
resource "aws_ebs_volume" "data" {
  count             = 3
  availability_zone = module.cassandra_fleet[count.index].availability_zone
  size              = 1000
  type              = "gp3"
  encrypted         = true
  
  tags = {
    Name = "prod-data-${count.index + 1}"
  }
}

resource "aws_volume_attachment" "data_att" {
  count       = 3
  device_name = "/dev/sdf"
  volume_id   = aws_ebs_volume.data[count.index].id
  instance_id = module.cassandra_fleet[count.index].id
}

output "node_ips" {
  value = module.cassandra_fleet[*].private_ip
}
