# Auto-generated by OmniCloud Ops at 2025-12-09T13:00:37.269Z
# Cluster: test


provider "aws" {
  region = "us-east-1"
}

module "cassandra_cluster" {
  source = "github.com/Gorak4u/terraform-aws-cassandra"

  cluster_name    = "test"
  environment     = "dev"
  instance_type   = "r5.2xlarge"
  node_count      = 3
  
  vpc_id          = "vpc-0a1b2c3d"
  subnet_ids      = ["subnet-1a","subnet-1b","subnet-1c"]
  security_groups = ["sg-db-access","sg-ssh-bastion"]
  
  # Storage
  root_volume_size = 50
  root_volume_type = "gp3"
  data_volume_size = 1000
  data_volume_type = "gp3"
  
  # Cassandra Config
  cassandra_version = "4.1.3"
  heap_size         = "32G"
  
  # LINKING PUPPET: Pass the bootstrap script to the instance
  user_data = file("${path.module}/../../bootstrap.sh")
  
  tags = {
    ManagedBy = "OmniCloud"
    CostCenter = "InfraOps"
    ManagedBy = "OmniCloud"
  }
}

output "private_ips" {
  value = module.cassandra_cluster.private_ips
}
